[package]
name = "azart_app"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
bevy = { version = "0.15.3", default-features = false, features = ["bevy_winit", "webgpu", "bevy_window", "bevy_asset", "bevy_gltf", "multi_threaded"] }
color-eyre = "0.6.3"
winit = "0.30.9"
gpu-allocator = "0.27.0"
thiserror = "2.0.12"
bytemuck = "1.22.0"
bitflags = "2.9.0"

[build-dependencies]
color-eyre = "0.6.3"

[profile.dev]
incremental = true
lto = false
